name: CI pipeline
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Printing a message
              run: echo "Hello, World!"
            - name: List files
              run: ls -la
            - name: Print workflow event
              run: echo "${{ github.event_name }}"
            - name: Show Github workspace
              run: echo "${{ github.workspace }}"
            - name: Show Runner OS
            
